name: 🐛 Bug Report
description: Report a bug or issue with Neural Operator Foundation Lab
title: "[BUG] "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the form below with as much detail as possible.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported already
          required: true
        - label: I have checked the documentation and FAQ
          required: true
        - label: I can reproduce this bug consistently
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Import neural_operator_lab
        2. Create model with parameters...
        3. Run training with...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Actual behavior...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Code Example
      description: Please provide a minimal code example that reproduces the issue
      render: python
      placeholder: |
        import neural_operator_lab as nol
        # Your minimal code example here
    validations:
      required: false

  - type: textarea
    id: error
    attributes:
      label: Error Message/Traceback
      description: If applicable, paste the full error message or traceback
      render: shell
      placeholder: Paste error message here...
    validations:
      required: false

  - type: dropdown
    id: version
    attributes:
      label: Neural Operator Lab Version
      description: Which version of the library are you using?
      options:
        - "Latest from main branch"
        - "1.0.0"
        - "0.9.0"
        - "0.8.0"
        - "Other (please specify in additional context)"
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: Which Python version are you using?
      options:
        - "3.11"
        - "3.10"
        - "3.9"
        - "Other (please specify in additional context)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - "Linux"
        - "macOS"
        - "Windows"
        - "Other (please specify in additional context)"
    validations:
      required: true

  - type: dropdown
    id: hardware
    attributes:
      label: Hardware
      description: What hardware are you running on?
      options:
        - "CPU only"
        - "NVIDIA GPU"
        - "AMD GPU"
        - "Apple Silicon (M1/M2)"
        - "Other (please specify in additional context)"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Additional environment information (PyTorch version, CUDA version, etc.)
      placeholder: |
        PyTorch version: 2.1.0
        CUDA version: 12.1
        GPU: RTX 4090
        RAM: 32GB
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional context, screenshots, or information that might be helpful
      placeholder: Add any other context about the problem here...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to help fix this bug
          required: false