apiVersion: v1
kind: Service
metadata:
  name: neural-operator-service
  namespace: neural-operator
  labels:
    app: neural-operator
    component: training
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  - name: distributed
    port: 29500
    targetPort: distributed
    protocol: TCP
  selector:
    app: neural-operator
    component: training

---
apiVersion: v1
kind: Service
metadata:
  name: neural-operator-headless
  namespace: neural-operator
  labels:
    app: neural-operator
    component: training
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: distributed
    port: 29500
    targetPort: distributed
    protocol: TCP
  selector:
    app: neural-operator
    component: training

---
apiVersion: v1
kind: Service
metadata:
  name: neural-operator-external
  namespace: neural-operator
  labels:
    app: neural-operator
    component: training
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    targetPort: http
    protocol: TCP
  selector:
    app: neural-operator
    component: training